### ISSUE TITLE
addgreeting confirmation has a typo

### ISSUE THREAD

**Issue by CoMiGa** [whatagoodbot/client-ttl#12]
The confirmation for addgreeting says "greating" it should be "greeting" current example "text greating added for CoMiGa"

**Comment by notABluesSinger** [comment]
Strings are stored in a database, so this has been updated - thanks for raising @CoMiGa

**Comment by CoMiGa** [comment]
@notABluesSinger still seeing this in metal-symposium
Miss Groupie
Today at 01:08 PM
text greating added for comiga
