### ISSUE TITLE
Roomstats spins is not accurate

### ISSUE THREAD

**Issue by CoMiGa** [whatagoodbot/client-ttl#14]
Roomstats is not showing a correct spins count

Example from metal-symposium

Miss Groupie
Today at 04:11 PM
This month, the room has a total of 0 nopes
Miss Groupie
Today at 04:11 PM
This month, the room has had 0 spins
Miss Groupie
Today at 04:11 PM
This month, the room has a total of 3 stars
Miss Groupie
Today at 04:11 PM
This month, the room has a total of 93 dope

**Comment by notABluesSinger** [comment]
@CoMiGa - I think this is resolved - please check and let me know if you still have issues and I can re-open this.

**Comment by CoMiGa** [comment]
@notABluesSinger it looks good to me now:
Miss Groupie
Today at 01:03 PM
This month, the room has had 223 spins
Miss Groupie
Today at 01:03 PM
This month, the room has a total of 194 dopes
Miss Groupie
Today at 01:03 PM
This month, the room has a total of 0 nopes
Miss Groupie
Today at 01:03 PM
This month, the room has a total of 9 stars

**Comment by notABluesSinger** [comment]
I've just checked in the db - right now there are;
- 284 spins
- 409 dopes
- 0 nopes
- 18 stars

Running roomstats gives me
This month, the room has had 284 spins
This month, the room has a total of 409 dopes
This month, the room has a total of 0 nopes
This month, the room has a total of 18 stars

So agree - all good. Thanks
